app:
  poll_interval_seconds: 5
  output_dir: data/output
  logs_dir: data/logs
  excel_sheet_name: Tardies
  weekday_only: true
  timezone: local

api:
  token_endpoint: "/v1/auth/token"
  attendance_path: "/v1/periodAttendance"
  attendance_since_param: "since"
  student_by_id_path: "/v1/students/{id}"
  student_enrollments_path: "/v1/students/{id}/schoolEnrollments"

excel:
  filename_pattern: "TardyLogs_{YYYY}-{WW}.xlsx"
  headers: ["Name", "ID", "Grade", "Timestamp", "Date"]
  date_format: "%Y-%m-%d"